FROM centos:7
MAINTAINER Tayl0r dangtuo888@gmail.com
RUN mkdir -p /var/develop  && yum -y install wget vim net-tools
RUN cd /var/develop && wget https://qc4.androidfilehost.com/dl/Rz7S5_RTGfjfxRQd4Osang/1550462627/1395089523397886194/lineage-16.0-20190206_155036-UNOFFICIAL-fajita.zip
