FROM centos:7
MAINTAINER Tayl0r dangtuo888@gmail.com
RUN mkdir -p /var/develop
RUN cd /var/develop && wget https://phoenixnap.dl.sourceforge.net/project/havoc-os/fajita/Havoc-OS-v2.2-20190206-fajita-Official.zip
