FROM centos:7
MAINTAINER Tayl0r dangtuo888@gmail.com
RUN mkdir -p /var/develop  && yum -y install wget vim net-tools
RUN wget https://www.percona.com/downloads/Percona-XtraDB-Cluster-57/Percona-XtraDB-Cluster-5.7.14-26.17/binary/tarball/Percona-XtraDB-Cluster-5.7.14-rel8-26.17.1.Linux.x86_64.ssl101.tar.gz
